spring:
    datasource:
        url: jdbc:mysql://localhost:8080/newdb
        username: root
        password: focamonaca
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: francesco
    jpa:
        database: myqsl
        show_sql: true
        hibernate:
            ddl-auto: create-drop

